CREATE DATABASE JSANCHEZCRUDEMPLEADO
USE JSANCHEZCRUDEMPLEADO
GO

CREATE TABLE EMPLEADO
(
IDEMPLEADO INT IDENTITY(1,1) PRIMARY KEY,
NOMBRE VARCHAR(50),
APELLIDOPATERNO VARCHAR(50),
APELLIDOMATERNO VARCHAR(50),
ESTATUS SMALLINT
)
GO

CREATE PROCEDURE EmpleadoAdd
@NOMBRE VARCHAR(50),
@APELLIDOPATERNO VARCHAR(50),
@APELLIDOMATERNO VARCHAR(50),
@ESTATUS SMALLINT
AS
INSERT INTO EMPLEADO(NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO,ESTATUS)
VALUES (@NOMBRE,@APELLIDOPATERNO,@APELLIDOMATERNO,@ESTATUS)
GO

CREATE PROCEDURE EmpleadoUpdate
@IDEMPLEADO INT,
@NOMBRE VARCHAR(50),
@APELLIDOPATERNO VARCHAR(50),
@APELLIDOMATERNO VARCHAR(50),
@ESTATUS SMALLINT
AS
UPDATE EMPLEADO SET
NOMBRE=@NOMBRE,
APELLIDOPATERNO=@APELLIDOPATERNO,
APELLIDOMATERNO=@APELLIDOMATERNO,
ESTATUS=@ESTATUS
WHERE IDEMPLEADO=@IDEMPLEADO
GO

CREATE PROCEDURE EmpleadoGetAll
@ESTATUS SMALLINT
AS
IF(@ESTATUS = 0)
SELECT IDEMPLEADO,NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO,ESTATUS FROM EMPLEADO
ELSE
SELECT IDEMPLEADO,NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO,ESTATUS FROM EMPLEADO WHERE ESTATUS = 1
GO

CREATE PROCEDURE EmpleadoGetById
@IDEMPLEADO INT
AS
SELECT IDEMPLEADO,NOMBRE,APELLIDOPATERNO,APELLIDOMATERNO,ESTATUS FROM EMPLEADO WHERE IDEMPLEADO=@IDEMPLEADO
GO

CREATE PROCEDURE EmpleadoDelete
@IDEMPLEADO INT
AS
UPDATE EMPLEADO SET ESTATUS=0 WHERE IDEMPLEADO=@IDEMPLEADO
GO